Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index', as: 'index'

  get 'maptrip(/:id)' => 'trips#maptrip', defaults: {format: :json}

  get 'users/:id/trips' => 'trips#user_list', as: 'trip_from_user'

  get 'trips/index' => 'trips#index', as: 'trip_index'
  get 'trips/new' => 'trips#new', as: 'create_new_trip'

  resources :trips do
    resources :stages do
      resources :image_stage
      resources :stage_comments
    end
  end

end

Project/app/models/stage.rb
class Stage < ActiveRecord::Base

  belongs_to :trip
  belongs_to :stagetype

  has_many :image_stages, :dependent => :delete_all
  has_many :stage_comments, :dependent => :delete_all

  validates :title,
            presence: true,
            length: {minimum: 0, maximum: 255}
  validates :description,
            length: {minimum: 0, maximum: 65535}
  validates :adress,
            length: {minimum: 0, maximum: 255}
  validates :date_time,
            presence: true
  validates :stagetype_id,
            presence: true

end

Project/app/models/stagetype.rb
class Stagetype < ActiveRecord::Base
  has_many :stages

  validates :title,
            presence: true
  validates :icon,
            presence: true
end

Project/app/controllers/stages_controller.rb
class StagesController < ApplicationController

  before_action :get_trip , only: [:create, :destroy, :edit, :update]
  before_action :identificate_user , only: [:create, :destroy, :edit]


  def identificate_user

    if !user_signed_in? || current_user != @trip.user
      flash[:notice] = t('not_allowed')
      redirect_to @trip
    end

  end

  def get_trip
    @trip = nil
    if params[:trip_id]
      @trip = Trip.find(params[:trip_id])
    end
  end

  def create
    @stage = Stage.new(stage_params)
    @stage.trip = @trip
    if @stage.save

      if params[:images]
        params[:images].each { |image|
          @stage.image_stages.create(image: image)
        }
      end

      redirect_to @trip
    else
      flash[:alerts] = @stage.errors.full_messages

      @my_stages = @trip.stages.order(:date_time).reverse_order
      render template: "trips/show"
    end
  end

  def destroy
    stage = Stage.find(params[:id])
    stage.destroy
    redirect_to @trip
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    stage = Stage.find(params[:id])

    if params[:images]
      params[:images].each { |image|
        stage.image_stages.create(image: image)
      }
    end

    if stage.update_attributes(stage_params)
      # Handle a successful update.
      redirect_to @trip
    else
      render 'edit'
    end

  end

  def stage_params
    params.require(:stage).permit([:title, :description, :adress, :date_time, :trip_id, :image, :stagetype_id, :score])
  end

end

Project/app/views/stages/_index.erb
<section id="articles">

  <% if @my_stages.empty? %>
      <p><%= t('nostage') %></p>

  <% else %>
    <% @my_stages.each do |stage| %>

      <section class="article-line">
        <article class="article-all-content">
          <div class="article-box">

            <% if !stage.image_stages.empty?  %>
              <div class="article-gallery">

                <a href="<%= stage.image_stages[0].image.url(:big) %>" class="imgLink">
                  <%= image_tag stage.image_stages[0].image.url(:small), :class => "article-img" %>
                </a>
                <div class="article-gallery-thumbs">
                  <% stage.image_stages.each do |photo| %>
                    <a href="<%= photo.image.url(:big) %>" class="imgLink">
                      <%= image_tag photo.image.url(:thumb), :class => "article-img-thumb" %>
                    </a>
                  <%end%>
                </div>
              </div>
            <%end%>

            <div class="article-content">

              <h1><%= stage.title %></h1>
              <p class="article-descr"><%= stage.description %>

              <div class="article-bottom">
                <p class="article-score">
                  <% if stage.score != 0 %>
                      <span class="stars-container stars-<%= stage.score %>">★★★★★</span>
                  <% end %>
                </p>
              <p class="article-lieu"><i class="fa fa-comment" aria-hidden="true"></i>

                <%= link_to pluralize(stage.stage_comments.size, 'comment', 'comments'),
                            comments_for_stage_path(@trip, stage) %>
                <%= link_to t('Write a comment'), new_trip_stage_stage_comment_path(@trip, stage) %>
              </p>
              <p class="article-lieu"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= stage.adress %></p>
            </div>

            </div>
          </div>
          <% if current_user == @trip.user && !current_user.nil? %>
            <div class="article-control">
              <%= link_to t('edit'),
                          edit_trip_stage_path(@trip, stage),
                          :class=>"article-control-btn"%>
              <%= link_to t('delete'),
                          [@trip, stage],
                          :confirm => t('confirm'),
                          :method => :delete,
                          :class=>"article-control-btn"%>
            </div>
          <% end %>
        </article>

        <div class="article-chronology">
          <div class="article-chronology-line">&nbsp;</div>
          <div class="article-chronology-logo"><i class="fa <%= stage.stagetype.icon %>"></i></div>
          <div class="article-chronology-date"><p><%= stage.date_time.strftime('%d.%m.%Y') %> <br/> <%=stage.date_time.strftime('%H:%M')%> </p></div>
        </div>
      </section>

    <% end %>
  <% end %>



</section>

Project/app/views/stages/_trip_stage.erb
<section class="article-line" id="stage<%= stage.id %>">
  <article class="article-all-content">
    <div class="article-box">

      <% if !stage.image_stages.empty?  %>
        <div class="article-gallery">

          <a href="<%= stage.image_stages[0].image.url(:big) %>" class="imgLink">
            <%= image_tag stage.image_stages[0].image.url(:small), :class => "article-img" %>
          </a>
          <div class="article-gallery-thumbs">
            <% stage.image_stages.each do |photo| %>
              <a href="<%= photo.image.url(:big) %>" class="imgLink">
                <%= image_tag photo.image.url(:thumb), :class => "article-img-thumb" %>
              </a>
            <%end%>
          </div>
        </div>
      <%end%>

      <div class="article-content">

        <h1><%= stage.title %></h1>
        <p class="article-descr"><%= stage.description %>

        <div class="article-bottom">
          <div class="article-little-infos">
            <div class="article-little-logo"><i class="fa <%= stage.stagetype.icon %>"></i></div>
            <div class="article-little-date"><p><%=stage.date_time.strftime('%H:%M')%> <br/> <%= stage.date_time.strftime('%d.%m.%Y') %> </p></div>
          </div>

          <p class="article-score">
            <% if stage.score != 0 %>
                <span class="stars-container stars-<%= stage.score %>">★★★★★</span>
            <% end %>
          </p>
        <p class="article-lieu"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= stage.adress %></p>
      </div>

    </div>

    </div>
    <% if current_user == @trip.user && !current_user.nil? %>
      <div class="article-control">
        <%= link_to t('edit'),
                    edit_trip_stage_path(@trip, stage),
                    :class=>"article-control-btn"%>
        <%= link_to t('delete'),
                    [@trip, stage],
                    data: {:confirm => t('stage_delete_confirm')},
                    :method => :delete,
                    :class=>"article-control-btn"%>
      </div>
    <% end %>

    <div class="article-comments">
      <% stage.stage_comments.each do |comment| %>
        <div class="article-comment">
          <i class="fa fa-comment comment-logo" aria-hidden="true"></i>

          <h2><i class="fa fa-user" aria-hidden="true"></i> <%= comment.user.username %></h2>

          <p><%= comment.content %></p>
          <p class="article-lieu">
            <%= comment.created_at.strftime("%d/%m/%y - %H:%M") %>
          </p>
        </div>
      <% end %>
    </div>

    <div class="article-comment-ctrl">
      <p><i class="fa fa-pencil" aria-hidden="true"></i> <%= link_to t('stage_comment_write_link'), new_trip_stage_stage_comment_path(@trip, stage) %></p>
    </div>

    <div class="article-comment-ctrl article-comment-show">
      <p><i class="fa fa-comments" aria-hidden="true"></i>
      <%= pluralize(stage.stage_comments.size, t('stage_comment_singular'), t('stage_comment_plural')) %></p>
    </div>

  </article>

  <div class="article-chronology">
    <div class="article-chronology-line">&nbsp;</div>
    <div class="article-chronology-logo"><i class="fa <%= stage.stagetype.icon %>"></i></div>
    <div class="article-chronology-date"><p><%= stage.date_time.strftime('%d.%m.%Y') %> <br/> <%=stage.date_time.strftime('%H:%M')%> </p></div>
  </div>
</section>

Project/app/views/stages/edit.html.erb
<% content_for :title, t('editArticle') %>

<%= render 'trips/header', :trip => @trip %>

<section class="trip-frm">
  <div id="trip-insert-center">
    <h2><%= t('editArticle') %></h2>

    <%= form_for [@trip, @stage], :html => { multipart: true } do |f| %>

        <div class="colx2-container">
          <div class="colx2">
            <%= f.label :title %><br />
            <%= f.text_field :title %><br />

            <%= f.label :description %><br />
            <%= f.text_area :description %><br />

            <%= f.label :stagetype_id %><br />

            <% Stagetype.all.each do |type| %>
                <div class="trip-insert-radio">
                  <input class="rbtn" type="radio" name="stage[stagetype_id]" value="<%=type.id%>"
                    <% if type==@stage.stagetype %>
                      <%= "checked" %>
                    <%end%>
                  />
                  <span><i class="fa <%=type.icon%>"></i> <%=type.title%></span>
                </div>
            <% end %>
          </div>
          <div class="colx2 col2">
            <%= f.label :adress %><br />
            <div id="find-mapsAPI">
              <input type="text" name="find_addr" id="find_addr" value="<%= @stage.adress %>" />
              <div class="find-btn"><i class="fa fa-search"></i></div>
            </div>

            <div id="finded_adresses"></div>
            <p id="nb_results"></p>

            <%= f.label :date_time %><br />
            <%= f.datetime_select :date_time, :order => [:day, :month, :year, :hour, :minute] %><br /><br />

            <%= f.label :score %> (<%= t('stage_no_score')%>)<br />
            <%= f.range_field :score, in: 0..5, step: 1, :oninput => "sliderShowValue(this.value)", :value => @stage.score %> <span id="score"><%= @stage.score %></span><br /><br />

            <label><%=t('add_images')%></label><br />
            <%= file_field_tag "images[]", type: :file, multiple: true %> <br />

            <label><%=t('current_images')%></label><br />
            <div class="images-ctrl">
            <%  @stage.image_stages.each do |photo| %>
              <div class="image-ctrl">
                <%= image_tag photo.image.url(:thumb) %>
                <%= link_to '',
                      [@trip, @stage, photo],
                      :confirm => t('confirm'),
                      :method => :delete,
                      :class=>"fa fa-trash image-ctrl-btn"%>
                </div>
            <%end%>
            </div>


          </div>
        </div>
        <div class="center-text-content">


          <%= link_to(@trip) do %>
              <div class="button-inline">
                <i class="fa fa-chevron-circle-left" aria-hidden="true"></i> <%=t('cancel')%>
              </div>
          <% end %>

          <%= f.submit t('save') %>
        </div>

    <% end %>

    <% if flash[:alerts] %>
        <ul>
          <% flash[:alerts].each do |alert| %>
              <li><%= alert %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
</section>

<%= javascript_include_tag 'trip_frm'%>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1Dp3v9OvUEEhePVbi3FoKCHrwpC2Yhhs&callback=initGeoEdit">
</script>