Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index', as: 'index'

  get 'maptrip(/:id)' => 'trips#maptrip', defaults: {format: :json}

  get 'users/:id/trips' => 'trips#user_list', as: 'trip_from_user'

  get 'trips/index' => 'trips#index', as: 'trip_index'
  get 'trips/new' => 'trips#new', as: 'create_new_trip'

  resources :trips do
    resources :stages do
      resources :image_stage
      resources :stage_comments
    end
  end

end

Project/app/views/layouts/_footer.html.erb
<footer>
  <div id="footer-center">

    <div class="footer-col col1">
      <h2><%= t('footer_promo_title') %></h2>
      <p> <i class="fa fa-user" aria-hidden="true"></i> <%= t('footer_join_us') %>
        <br/> <i class="fa fa-globe" aria-hidden="true"></i> <%= t('footer_create_trip') %>
        <br/> <i class="fa fa-comment" aria-hidden="true"></i> <%= t('footer_share_experiences') %>
        <br /> <i class="fa fa-eye" aria-hidden="true"></i> <%= t('footer_friends_trips') %>
        <br /> <i class="fa fa-plus" aria-hidden="true"></i> <%= t('footer_more') %> </p>
    </div>

    <div class="footer-col col2">
      <p class="footer-citation"><br/><%= t('footer_citation') %></p>
      <p class="footer-citation-author"><i>(<%= t('footer_author') %>)</i></p>
    </div>

    <div class="footer-col col3">
      <h2><%= t('footer_about_us_title') %></h2>
      <p>
      Margaux Divernois <i class="fa fa-user" aria-hidden="true"></i><br/>
      Steve Visinand <i class="fa fa-user" aria-hidden="true"></i></p>

      <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> All right reserved<br/>
    </div>

  </div>
</footer>

Project/app/views/layouts/_stages.erb
<section id="articles">

  <% if @my_stages.empty? %>
      <p><%= t('nostage') %></p>

  <% else %>
    <% @my_stages.each do |stage| %>

      <section class="article-line">
        <article class="article-all-content">
          <div class="article-box">

            <% if !stage.image_stages.empty?  %>
              <div class="article-gallery">

                <a href="<%= stage.image_stages[0].image.url(:big) %>" class="imgLink">
                  <%= image_tag stage.image_stages[0].image.url(:small), :class => "article-img" %>
                </a>
                <div class="article-gallery-thumbs">
                  <% stage.image_stages.each do |photo| %>
                    <a href="<%= photo.image.url(:big) %>" class="imgLink">
                      <%= image_tag photo.image.url(:thumb), :class => "article-img-thumb" %>
                    </a>
                  <%end%>
                </div>
              </div>
            <%end%>

            <div class="article-content">

              <h1><%= stage.title %></h1>
              <p class="article-descr"><%= stage.description %>

              <p class="article-score">
                <% if stage.score != 0 %><span class="stars-container stars-<%= stage.score %>">★★★★★</span><% end %></p>
              </p>
              <p class="article-lieu"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= stage.adress %></p>

            </div>
          </div>
          <% if current_user == @trip.user && !current_user.nil? %>
            <div class="article-control">
              <%= link_to t('edit'),
                          edit_trip_stage_path(@trip, stage),
                          :class=>"article-control-btn"%>
              <%= link_to t('delete'),
                          [@trip, stage],
                          :confirm => t('confirm'),
                          :method => :delete,
                          :class=>"article-control-btn"%>
            </div>
          <% end %>
        </article>

        <div class="article-chronology">
          <div class="article-chronology-line">&nbsp;</div>
          <div class="article-chronology-logo"><i class="fa <%= stage.stagetype.icon %>"></i></div>
          <div class="article-chronology-date"><p><%= stage.date_time.strftime('%d.%m.%Y') %> <br/> <%=stage.date_time.strftime('%H:%M')%> </p></div>
        </div>
      </section>

    <% end %>
  <% end %>



</section>

Project/app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport"	content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes"/>
  <title><%= t('website_title') %> - <%= yield(:title) %></title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "styles.css" %>
  <%= stylesheet_link_tag "lightgallery.js" %>
</head>

<body>
<header id="head-top">

  <div id="head-top-center">

      <div id="head-top-logo"><i class="fa fa-globe"></i></div>

      <p id="head-top-title"><a href="<%=index_path()%>"><%= t('website_title') %></a></p>

      <div class="head-top-nav">


        <div id="button-open-pannel">

          <% if user_signed_in? %>
              <p><i class="fa fa-user"></i></p>
          <% else %>
              <p><i class="fa fa-sign-in"></i></p>
          <% end %>

        </div>

      </div>

  </div>

</header>

<% flash.each do |name, msg| %>
      <% if msg.class == Array %>
          <div class="<%= name %>"><div class="center-content"><p>
          <% msg.each do |message| %>
                <i class="fa fa-exclamation-triangle"></i> <%= message %><br/>
          <% end %>
          </p></div></div>
      <% else %>
        <div class="<%= name %>"><div class="center-content"><p><i class="fa fa-exclamation-triangle"></i> <%= msg %></p></div></div>
      <% end %>
<% end %>
<% flash = nil %>


<section id="user-pannel">
  <div class="center-content">
    <% if user_signed_in? %>
      <div id="button-little">
        <%= link_to 'Create Trip', create_new_trip_path() %>
      </div>
      <div id="button-little">
        <%= link_to 'My Trips', trip_from_user_path(current_user.id) %>
      </div>
      <div id="button-little">
        <%= link_to 'Logout', destroy_user_session_url, :method => :delete %>
      </div>
      <div id="info-user">
        <p><%= current_user.username %></p>
      </div>
      <i class="fa fa-user" id="icon-user"></i>

    <% else %>

      <div id="button-little">
        <%= link_to 'Login', user_session_url %>
      </div>
      <div id="button-little">
         <%= link_to 'Subscribe', new_user_registration_url %>
      </div>

    <% end %>
  </div>
</section>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>