Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index', as: 'index'

  get 'maptrip(/:id)' => 'trips#maptrip', defaults: {format: :json}

  get 'users/:id/trips' => 'trips#user_list', as: 'trip_from_user'

  get 'trips/index' => 'trips#index', as: 'trip_index'
  get 'trips/new' => 'trips#new', as: 'create_new_trip'

  resources :trips do
    resources :stages do
      resources :image_stage
      resources :stage_comments
    end
  end

end

Project/app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :stages
  belongs_to :user

  validates :title,
            presence: true,
            length: {minimum: 0, maximum: 255}
  validates :description,
            length: {minimum: 0, maximum: 65535}

  validates_uniqueness_of :title, :scope => :user_id

  attr_accessible :title, :description, :date_start, :date_end, :main_country, :image

  has_attached_file :image, styles: { big: "600x450#", medium: "150x150#", small: "80x80#"}, default_url: "/images/:style/trip_missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def country_name
    ISO3166::Country[main_country]
  end

  def image_url
    return image.url(:medium)
  end

end

Project/app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.all
  end

  def user_list
    @trips = Trip.where(:user_id => params[:id])
  end

  def show
    @trip = Trip.find(params[:id])

    @stage = Stage.new
    @my_stages = @trip.stages.order(:date_time).reverse_order
  end

  def maptrip

    if !params.has_key?(:id)
      trip = Trip.offset(rand(Trip.count)).first
    else
      trip = Trip.find(params[:id])
    end

    response = { :trip => trip, :stages => trip.stages, :user => trip.user }
    respond_to do |format|
      format.json  { render :json => response.to_json(:methods => [:image_url, :country_name]) }
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    if current_user != nil
      @trip = Trip.new(params[:trip])
      @trip.user = current_user

      if @trip.save
        flash.notice = t('trip_creation_success')
        redirect_to action: :user_list, id: current_user.id
      else
        flash.alert = @trip.errors.full_messages
        redirect_to action: :new
      end
    else
      flash.alert = t('trip_creation_not_connected')
      redirect_to action: :index
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    if current_user != nil
      @trip = Trip.find(params[:id])
      if current_user.id == @trip.user_id
        if @trip.update(params[:trip])
          flash.notice = t('trip_edition_success')
          redirect_to action: :show, id: @trip.id
          else
            render 'edit'
        end
      else
        flash.alert = t('trip_edition_not_owner')
        redirect_to action: :user_list, id: current_user.id
      end
    else
      flash.alert = t('trip_edition_not_connected')
      redirect_to action: :index
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    if current_user != nil
      if current_user.id == @trip.user_id
        @trip.stages.each do |stage|
          stage.delete
        end
        Trip.find(params[:id]).delete
        flash.notice = t('trip_removal_success')
        redirect_to action: :user_list, id: current_user.id
      else
        flash.alert = t('trip_removal_not_owner')
        redirect_to action: :user_list, id: current_user.id
      end
    else
      flash.alert = t('trip_removal_not_connected')
      redirect_to action: :index
    end
  end

  def trip_params
    params.require(:trip).permit(:title, :description, :image)
  end

end

Project/app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>

    <div class="colx2-container">
      <div class="colx2">
        <%= f.label :title %>
        <%= f.text_field :title %><br />

        <%= f.label :description %>
        <%= f.text_area :description %><br />
      </div>
      <div class="colx2 col2">
        <div class="colx2-container">
          <div class="colx2">
            <%= f.label :date_start %><br />
            <%= f.date_select :date_start, :order => [:day, :month, :year] , :include_blank => true %>
          </div>
          <div class="colx2 col2">
            <%= f.label :date_end %><br />
            <%= f.date_select :date_end, :order => [:day, :month, :year] , :include_blank => true %>
          </div>
        </div>

        <p><%= f.label :main_country %><br/>
        <%= country_select("trip", "main_country") %><br /></p>

        <p><%= f.label :image %><br />
        <%= f.file_field :image %></p>
      </div>
    </div>

    <%= f.submit %>
<% end %>

Project/app/views/trips/_header.erb
<section id="head-travel">

  <div id="head-travel-center">

    <div id="head-travel-img"><%= image_tag @trip.image.url(:small) %></div>
    <div id="head-travel-descr">

      <span class="hidden" id="trip_id"><%= @trip.id %></span>

      <p><%= @trip.title %></p>
      <p><i class="fa fa-calendar"></i>
        <%= if !@trip.date_start.nil?
              @trip.date_start.strftime("%d/%m/%y")
            else
              t('trip_date_unknown')
            end %>
        -
        <%= if !@trip.date_end.nil?
              @trip.date_end.strftime("%d/%m/%y")
            else
              t('trip_date_unknown')
            end %>
        <br/></p>
      <p><i class="fa fa-user"></i>
        <%= @trip.user.username %></p>
    </div>

    <div id="head-travel-ctrl">

      <% if current_user == @trip.user && !current_user.nil? %>

          <a href="#" class="little-ctrl-button" id="open-frm-insert">
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
          </a>

          <a href="<%=edit_trip_path(@trip.id)%>" class="little-ctrl-button">
            <i class="fa fa-pencil"></i>
          </a>

          <%= link_to @trip, :method=>:delete, data: {:confirm => t('trip_delete_confirm')}, :class=>"little-ctrl-button" do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>

      <% end %>

    </div>
  </div>

</section>

Project/app/views/trips/_show_element.html.erb
<div class="display-box">
  <div class="display-box-top">
    <div>
      <%= image_tag trip.image.url(:big), alt: trip.title, id: trip.id, class: "display-box-img" %>
      <div class="display-box-content">
        <b><%= trip.title %></b><br/>
        <%= trip.description %><br/>
        <i class="fa fa-calendar"></i>
          <% if !trip.date_start.nil? %>
            <%= trip.date_start.strftime("%d/%m/%y") %>
          <% else %>
            <%= t('trip_date_unknown') %>
          <% end %>
          -
          <% if !trip.date_end.nil? %>
              <%= trip.date_end.strftime("%d/%m/%y") %>
          <% else %>
            <%= t('trip_date_unknown') %>
          <% end %>
          <br/>
        <i class="fa fa-globe"></i> <%= trip.country_name %>
      </div>
    </div>
  </div>
  <div class="display-box-buttons">
    <% if !current_user.nil? && current_user == trip.user %>
        <div class="display-box-buttons-left">
          <i class="fa fa-pencil"></i> <%= link_to t('trip_personnal_edit'), edit_trip_path(trip.id) %>
        </div>
    <% end %>
    <%= link_to(trip) do %>
        <div class="display-box-buttons-right">
          <%= t('trip_list_view') %>
        </div>
    <% end %>
  </div>
</div>

Project/app/views/trips/edit.html.erb
<% content_for :title, t('trip_update_title') %>

<%= render 'header', :trip => @trip %>

<div class="center-content">
  <h1><%= t('trip_update_title') %></h1>

  <%= render 'form' %>

  <br/>
  <%= button_to  t('trip_delete'), @trip, :method=>:delete, :class=>:destroy %>

  <br/>
</div>

Project/app/views/trips/index.html.erb
<% content_for :title, "Trips" %>

<div class="center-content">

  <h1><%= t('trip_title_all') %></h1>

  <% @trips.each do |trip| %>

      <%= render :template => 'trips/_show_element', :locals => { :trip => trip } %>

  <% end %>

  <% if @trips.empty? %>
    <p><%= t('trip_list_empty') %></p>
  <% end %>

</div>

Project/app/views/trips/new.html.erb
<% content_for :title, t('travel_create_title') %>

<div class="center-content">
  <h1><%= t('travel_create_title') %></h1>

  <%= render 'form' %>

  <br/>
</div>

Project/app/views/trips/show.html.erb
<% content_for :title, @trip.title %>

<%= render 'trips/header', :trip => @trip %>

<% if current_user == @trip.user && !current_user.nil? %>
  <section id="trip-insert-frm" class="trip-frm">
    <div id="trip-insert-center">
      <h2><%= t('insertArticle') %></h2>

      <%= form_for [@trip, @stage], :html => { multipart: true } do |f| %>

          <div class="colx2-container">
            <div class="colx2">
              <%= f.label :title %><br />
              <%= f.text_field :title %><br />

              <%= f.label :description %><br />
              <%= f.text_area :description %><br /><br />

              <%= f.label :score %> (<%= t('stage_no_score')%>)<br />
              <%= f.range_field :score, in: 0..5, step: 1, :oninput => "sliderShowValue(this.value)", :value => 0 %> <span id="score">0</span><br /><br />

              <%= f.label :stagetype_id %><br />

              <% Stagetype.all.each do |type| %>
                  <div class="trip-insert-radio">
                    <input class="rbtn" type="radio" name="stage[stagetype_id]" value="<%=type.id%>"
                           <% if type==@stage.stagetype %>
                           checked="checked"
                           <%end%>
                    />
                    <span><i class="fa <%=type.icon%>"></i> <%= type.title %></span>
                  </div>
              <% end %>
            </div>
            <div class="colx2 col2">
              <%= f.label :adress %><br />
              <div id="find-mapsAPI">
                <input type="text" name="find_addr" id="find_addr" />
                <div class="find-btn"><i class="fa fa-search"></i></div>
              </div>

              <div id="finded_adresses"></div>
              <p id="nb_results"></p>

              <%= f.label :date_time %><br />
              <%= f.datetime_select :date_time, :order => [:day, :month, :year, :hour, :minute] %><br /><br />

              <%= f.label :image %><br />

              <%= file_field_tag "images[]", type: :file, multiple: true %> <br />

            </div>
          </div>

          <div class="center-text-content">
            <%= f.submit t('insertButton') %>
          </div>
      <% end %>

    </div>
  </section>
<% end %>

<div id="map"></div>

<section id="articles-zone">

  <section id="articles">

    <% if @my_stages.empty? %>
        <p><%= t('nostage') %></p>

    <% else %>
        <% @my_stages.each do |stage| %>

            <%= render 'stages/trip_stage', :stage => stage %>

        <% end %>
    <% end %>

  </section>

  <section id="trip-description">
    <div class="trip-description-center">
      <div class="trip-description-content">

        <p><%= @trip.description %></p>
      </div>

    </div>
  </section>

</section>

<%= javascript_include_tag 'trip_frm'%>
<%= javascript_include_tag 'trip_map'%>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1Dp3v9OvUEEhePVbi3FoKCHrwpC2Yhhs&callback=initGeo">
</script>

Project/app/views/trips/show_trip_listing.html.erb
<div class="display-trip">
  <div class="display-trip-top">
    <div>
      <%= image_tag "http://www.officeholidays.com/images/slider/japan_03.jpg", alt: trip.title, id: trip.id, class: "display-trip-img" %>
      <div class="display-trip-content">
        <b><%= trip.title %></b><br/>
        <%= trip.description %><br/>
        <i class="fa fa-calendar"></i>
          <% if !trip.date_start.nil? %>
            <%= trip.date_start.strftime("%d/%m/%y") %>
          <% else %>
            <%= t('trip_date_unknown') %>
          <% end %>
          -
          <% if !trip.date_end.nil? %>
              <%= trip.date_end.strftime("%d/%m/%y") %>
          <% else %>
            <%= t('trip_date_unknown') %>
          <% end %>
          <br/>
        <i class="fa fa-globe"></i> <%= trip.main_country %>
      </div>
    </div>
  </div>
  <div class="display-trip-buttons">
    <div class="display-trip-buttons-left">
      <% if !current_user.nil? && current_user == trip.user %>
          <i class="fa fa-pencil"></i> <%= link_to t('trip_personnal_edit'), edit_trip_path(trip.id) %>
      <% else %>
          <i class="fa fa-star"></i> <%= link_to t('trip_list_follow') %>
      <% end %>
    </div>
    <%= link_to(trip) do %>
        <div class="display-trip-buttons-right">
          <%= t('trip_list_view') %>
        </div>
    <% end %>
  </div>
</div>

Project/app/views/trips/user_list.html.erb
<% content_for :title, t('trip_personnal_title') %>

<div class="center-content">
<h1><%= t('trip_personnal_title') %></h1>
  <% @trips.each do |trip| %>

      <%= render :template => 'trips/_show_element', :locals => { :trip => trip } %>

  <% end %>

  <% if @trips.empty? %>
    <p><%= t('trip_personnal_empty') %></p>

      <%= link_to t('trip_personnal_create_first'), create_new_trip_path(), { :class => 'button' } %>
  <% end %>
</div>