Project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#index', as: 'index'

  get 'maptrip(/:id)' => 'trips#maptrip', defaults: {format: :json}

  get 'users/:id/trips' => 'trips#user_list', as: 'trip_from_user'

  get 'trips/index' => 'trips#index', as: 'trip_index'
  get 'trips/new' => 'trips#new', as: 'create_new_trip'

  resources :trips do
    resources :stages do
      resources :image_stage
      resources :stage_comments
    end
  end

end

Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  end

  # before_action :configure_permitted_parameters, if: :devise_controller?
  # protected
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
  #   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  #   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  # end

  def index

    @last_stages = Stage.last(4).reverse
    @rand_trips = Trip.order('RAND()').limit(4)

  end

end

Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Project/app/views/application/index.html.erb
<% content_for :title, "Trips" %>

<section id="map-index-section">

  <div id="map">

  </div>

  <div id="tripInfo">
    <div id="trip-center">
      <div id="trip-box">


        <img id="trip-img" />
        <div id="trip-info">
          <h1 id="tripName">TRIP_NAME</h1>

          <table>

            <tr>
              <td align="center"><i class="fa fa-user" aria-hidden="true"></i></td>
              <td><p id="tripUserName">TRIP_USER</p></td>
            </tr>

            <tr>
              <td align="center"><i class="fa fa-map-marker" aria-hidden="true"></i></td>
              <td><p id="tripLocation">TRIP_LOCATION</p></td>
            </tr>

            <tr>
              <td align="center"><i class="fa fa-calendar" aria-hidden="true"></i></td>
              <td><p id="tripDate">TRIP_DATE</p></td>
            </tr>
          </table>

        </div>

        <a href="#" id="tripDiscoverButton" class="button btn-discover"><%= t('home_trip_discover') %></a>

      </div>

    </div>

  </div>

  <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1Dp3v9OvUEEhePVbi3FoKCHrwpC2Yhhs&callback=initGeo">
  </script>

</section>

<section class="last-articles">

  <div class="center-content">

    <h1 class="center-title"><%= t('home_last_articles' )%></h1>

    <div class="cards"><!--WHITESPACE

     <% @last_stages.each do |stage| %>

      --><a href="<%= trip_url(stage.trip) %>#stage<%= stage.id %>">
      <div class="article-apercu-card">

        <% if !stage.image_stages.empty?  %>
            <%= image_tag stage.image_stages[0].image.url(:big)%>
        <%end%>

        <i class="apercu-icon fa <%= stage.stagetype.icon %>"></i>

        <div class="apercu-content">
          <h1><%= stage.title %></h1>
          <h2><%= stage.trip.title %></h2>
          <p> <i class="fa fa-map-marker"></i> <%= stage.trip.country_name %></p>
          <p class="article-score">
          <% if stage.score != 0 %>
              <span class="stars-container stars-<%= stage.score %>">★★★★★</span>
          <% end %>
          </p>
        </div>

      </div>
    </a><!--WHITESPACE

     <% end %>

     --></div>

  </div>

</section>

<section class="section-travels">

  <div class="center-content">

    <h1 class="center-title"><%=t('trips')%></h1>

    <div class="cards"><!--WHITESPACE

     <% @rand_trips.each do |trip| %>

      --><a href="<%= trip_url(trip) %>">
      <div class="article-apercu-card">

        <%= image_tag trip.image.url(:big)%>

        <div class="apercu-content">
          <h1><%= trip.title %></h1>
          <p> <i class="fa fa-map-marker"></i> <%= trip.country_name %></p>
        </div>

      </div>
    </a><!--WHITESPACE

     <% end %>


     --></div>

    <div>


    </div>

    <div class="center-text-content">
      <%= link_to t('home_all_travels'), trip_index_path, :class => "button-large" %>
    </div>

  </div>

</section>